service: temperature-monitor-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  submitMeasurement:
    handler: src/measurements.submit
    description: Submit temperature for a given sensor
    events:
      - http:
          path: measurements/submit/{sensorId}
          method: get
  queryLastMeasurement:
    handler: src/measurements.queryLast
    description: Query the last temperature submited for a given sensor
    events:
      - http:
          path: measurements/last/{sensorId}
          method: get
  queryPeriodMeasurement:
    handler: src/measurements.queryPeriod
    description: Query the temperatures submited for a given sensor and a time period from now backwards
    events:
      - http:
          path: measurements/period/{sensorId}
          method: get
  submitRange:
    handler: src/ranges.submit
    description: Submit valid range for a given sensor
    events:
      - http:
          path: ranges/submit/{sensorId}
          method: post
  queryLastRange:
    handler: src/ranges.queryLast
    description: Query the last range submited for a given sensor
    events:
      - http:
          path: ranges/last/{sensorId}
          method: get
  submitSetting:
    handler: src/settings.submit
    description: Submit a setting
    events:
      - http:
          path: settings/submit
          method: post
  telegramSubscribe:
    handler: src/telegramSubscriptions.subscribe
    description: Subscribe to receive notifications for a sensor
    events:
      - http:
          path: telegram-subscriptions/subscribe/{sensorId}/{chatId}
          method: post
  telegramUnsubscribe:
    handler: src/telegramSubscriptions.unsubscribe
    description: Unsubscribe to stop receiving notifications for a sensor
    events:
      - http:
          path: telegram-subscriptions/unsubscribe/{sensorId}/{chatId}
          method: post

resources:
  Resources:
    MeasurementsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: measurements
        AttributeDefinitions:
          -
            AttributeName: "sensorId"
            AttributeType: "S"
          -
            AttributeName: "timestamp"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "sensorId"
            KeyType: "HASH"
          -
            AttributeName: "timestamp"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    RangeDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ranges
        AttributeDefinitions:
          -
            AttributeName: "sensorId"
            AttributeType: "S"
          -
            AttributeName: "timestamp"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "sensorId"
            KeyType: "HASH"
          -
            AttributeName: "timestamp"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SettingsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: settings
        AttributeDefinitions:
          -
            AttributeName: "key"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "key"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TelegramSubscriptionsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: telegram_subscriptions
        AttributeDefinitions:
          -
            AttributeName: "sensorId"
            AttributeType: "S"
          -
            AttributeName: "chatId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "sensorId"
            KeyType: "HASH"
          -
            AttributeName: "chatId"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
